export const capacityPoolABI = [
  {
    anonymous: false,
    inputs: [
      {
        components: [
          { internalType: "string", name: "id", type: "string" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "state", type: "uint256" },
          { internalType: "uint256", name: "expiryTimestamp", type: "uint256" },
          { internalType: "address", name: "buyer", type: "address" },
        ],
        indexed: false,
        internalType: "struct CapacityPool.Offer",
        name: "offer",
        type: "tuple",
      },
    ],
    name: "OfferUpdated",
    type: "event",
  },
  {
    inputs: [{ internalType: "string", name: "offerId", type: "string" }],
    name: "acceptOffer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "id", type: "string" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "uint256", name: "expiryTimestamp", type: "uint256" },
    ],
    name: "addOffer",
    outputs: [
      {
        components: [
          { internalType: "string", name: "id", type: "string" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "state", type: "uint256" },
          { internalType: "uint256", name: "expiryTimestamp", type: "uint256" },
          { internalType: "address", name: "buyer", type: "address" },
        ],
        internalType: "struct CapacityPool.Offer",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "offerId", type: "string" }],
    name: "getOffer",
    outputs: [
      {
        components: [
          { internalType: "string", name: "id", type: "string" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "state", type: "uint256" },
          { internalType: "uint256", name: "expiryTimestamp", type: "uint256" },
          { internalType: "address", name: "buyer", type: "address" },
        ],
        internalType: "struct CapacityPool.Offer",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "offerId", type: "string" }],
    name: "getOfferIndex",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOffers",
    outputs: [
      {
        components: [
          { internalType: "string", name: "id", type: "string" },
          { internalType: "address", name: "seller", type: "address" },
          { internalType: "uint256", name: "price", type: "uint256" },
          { internalType: "uint256", name: "state", type: "uint256" },
          { internalType: "uint256", name: "expiryTimestamp", type: "uint256" },
          { internalType: "address", name: "buyer", type: "address" },
        ],
        internalType: "struct CapacityPool.Offer[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOffersLength",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "offerId", type: "string" }],
    name: "isExpired",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "id", type: "string" }],
    name: "isOfferUnique",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "offers",
    outputs: [
      { internalType: "string", name: "id", type: "string" },
      { internalType: "address", name: "seller", type: "address" },
      { internalType: "uint256", name: "price", type: "uint256" },
      { internalType: "uint256", name: "state", type: "uint256" },
      { internalType: "uint256", name: "expiryTimestamp", type: "uint256" },
      { internalType: "address", name: "buyer", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "offerId", type: "string" }],
    name: "removeOffer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
];
